name: Test checkout
on:
  push:
    branches:
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    name: Echo branch
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls -alrt
      - run: ls -alrt
        working-directory: testdir
      - id: folders
        uses: philips-labs/list-folder-action@v1
        with:
          path: ./testdir
      - run: echo "${{ steps.folders.outputs }}"
