name: Test checkout
on:
  push:
    branches:
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    name: Echo branch
    defaults:
      run:
        working-directory: testdir
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls -alrt
      - run: ls -alrt
        working-directory: testdir
      - uses: valitydev/action-download-file@v1
        with:
          url: https://github.com/valitydev/action-download-file/raw/master/README.md
          target-path: .
      - run: ls -alrt
        working-directory: ./
      - run: echo "${{ steps.folders.outputs }}"
