name: Test tags
on:
  push:
    tags:
      - "*"
    branches:
      - "release/*"
jobs:
  echo:
    runs-on: ubuntu-latest
    name: Echo tags
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ toJSON(github) }}
